---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverybookapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deliverybookapi
    spec:
      containers:
      - name: deliverybookapi
        image: kuranaga/deliverybookapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: deliverybookapi
---
apiVersion: v1
kind: Service
metadata:
  name: deliverybookapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: deliverybookapi