image: node:latest

stages:
  - install
  - build
# - test
  - deploy

cache:
  paths:
    - build
    - node_modules/

install:
  stage: install
  script:
    - npm install --lts 

build:
  stage: build
  script:
      - npm run build

# test:
#   stage: test
#   script:
#     - npm run test

deploy:
  stage: deploy
  image: node:latest
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase use $PROJECT_NAME --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  only: 
    - master
